name: travell_apps
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  url_launcher: ^6.1.12
  google_fonts: ^5.1.0
  analyzer: ^5.7.1
  intl: ^0.18.0
  flutter:
    sdk: flutter
  dio: ^5.3.2
  cached_network_image: ^3.2.3
  neopop: ^1.0.2
  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - public/assets/fonts/
    - public/assets/images/
    - public/assets/app_icon/
    - lang/
    - .env
